### PR TITLE
OVN: Add external_ids

### PR DESCRIPTION
**Pull request by apevec**
https://bugs.launchpad.net/bugs/1740698

### CODE REVIEW

**Comment by apevec** [comment]
@numansiddique this can be dropped if 2.8.2 is released[1] and we can rebase

[1] requested in https://mail.openvswitch.org/pipermail/ovs-dev/2018-January/342516.html

**Comment by numansiddique** [comment]
@apevec Agree. Thanks for handling this in rdo until we have 2.8.2

**Comment by apevec** [comment]
external_ids was reintroduced again in https://review.openstack.org/#/c/528746/19/networking_ovn/ovsdb/commands.py@1034

Instead of patch networking-ovn again, going fwd with this planB

**Comment by apevec** [comment]
CBS build http://cbs.centos.org/koji/buildinfo?buildID=21347
being pushed to deps repo in https://review.rdoproject.org/r/11091

**Pull request merged**
